
name: .NET Core build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./Airtraffic
    - name: Build
      working-directory: ./Airtraffic
      run: dotnet build
    - name: Test
      run: |
        cd ./Airtraffic/Airtraffic.Tests
        dotnet test --no-restore --no-build --logger:"liquid.md;LogFileName=$'test output'"
    - name: Fly HTTP Post Request
      id: fly-request
      uses: fjogeleit/http-request-action@master
      with:
       url: 'https://acies-airtraffic.azurewebsites.net/api/glider/fly/51'
       method: 'POST'
       data:  '{ "destinationAirportId" : 100 }'    
    - name: Print response
      run: echo "${{ steps.fly-request.outputs.*}}"
