
name: .NET Core build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./Airtraffic
    - name: Build
      working-directory: ./Airtraffic
      run: dotnet build
    - name: Test
      run: |
        cd ./Airtraffic/Airtraffic.Tests
        dotnet test --no-restore --no-build --logger:"liquid.md;LogFileName=$'test output'"
    - name: Create flight HTTP Post Request
      id: create_flight
      uses: fjogeleit/http-request-action@master
      with:
       url: 'https://acies-airtraffic.azurewebsites.net/api/airplane'
       method: 'POST'
       data:  '{ "fuelConsumptionInKilometersPerLitre": 1337, "name": "Github Action Airplane 123", "airspeedInKilometersPerHour": 975, "pilotCount": 23, "airportId": 100 }'       
    - name: print id
      run: echo "${{ fromJSON(steps.create_flight.outputs.response) }}"
    - name: Fly HTTP Post Request
      id: fly_request
      uses: fjogeleit/http-request-action@master
      with:
       url: 'https://acies-airtraffic.azurewebsites.net/api/airplane/fly/${{ fromJSON(steps.create_flight.outputs.response) }}'
       method: 'POST'
       data:  '{ "destinationAirportId" : 99 }'    
    - name: Print response
      run: echo "${{steps.fly_request.outputs.response}}"
